"use client";
import { Suspense, useEffect, useRef, useState } from "react";
import { Canvas, useFrame, useLoader, type ThreeEvent } from "@react-three/fiber";
import { Box3, Group, MathUtils, Vector3 } from "three";
import { GLTFLoader } from "three/addons/loaders/GLTFLoader.js";
import { useGpuSceneActivity } from "@/hooks/useGpuSceneActivity";
import { gpuSceneConfig } from "@/lib/performance/gpu-config";
import StudioEnvironment from "../can/StudioEnvironment";
const config={scale:.42,baseY:(-35*Math.PI)/180,yaw:(5*Math.PI)/180,pitch:(1*Math.PI)/180,roll:(.5*Math.PI)/180,camera:[8,5,11] as const,floatAmplitude:.055,floatAngularVelocity:(2*Math.PI)/6.2,driftAmplitude:.07,driftAngularVelocity:(2*Math.PI)/8.5,ambientPitch:(.5*Math.PI)/180,ambientRoll:(.4*Math.PI)/180,ambientYaw:(1.25*Math.PI)/180} as const;
function Car({fine,reduced}:{fine:boolean;reduced:boolean}){const gltf=useLoader(GLTFLoader,"/models/playground/diecast/bmw-m3-gtr-v1.glb"),floatRoot=useRef<Group>(null),driftRoot=useRef<Group>(null),root=useRef<Group>(null),hit=useRef<Group>(null),target=useRef({x:0,y:0}),[box,setBox]=useState<Box3|null>(null);useEffect(()=>{gltf.scene.updateMatrixWorld(true);const b=new Box3().setFromObject(gltf.scene);setBox(b)},[gltf]);useFrame((state,d)=>{if(!root.current||!floatRoot.current||!driftRoot.current)return;const t=state.clock.elapsedTime;if(reduced){floatRoot.current.position.y=0;driftRoot.current.position.x=0;root.current.rotation.set(0,config.baseY,0);return}floatRoot.current.position.y=Math.sin(t*config.floatAngularVelocity)*config.floatAmplitude;driftRoot.current.position.x=Math.sin(t*config.driftAngularVelocity+.9)*config.driftAmplitude;root.current.rotation.y=MathUtils.damp(root.current.rotation.y,config.baseY+target.current.x+Math.sin(t*.53+1.1)*config.ambientYaw,6,d);root.current.rotation.x=MathUtils.damp(root.current.rotation.x,target.current.y+Math.sin(t*.71)*config.ambientPitch,6,d);root.current.rotation.z=MathUtils.damp(root.current.rotation.z,target.current.x*.1+Math.sin(t*.61+.4)*config.ambientRoll,6,d)});if(!box)return <primitive object={gltf.scene} scale={config.scale}/>;const size=box.getSize(new Vector3()),center=box.getCenter(new Vector3()),ground=-box.min.z*config.scale;return <group ref={hit}><mesh position={[center.x*config.scale,center.y*config.scale,0]} onPointerMove={(e:ThreeEvent<PointerEvent>)=>{if(fine&&!reduced){target.current.x=e.pointer.x*config.yaw;target.current.y=-e.pointer.y*config.pitch}}} onPointerLeave={()=>{target.current.x=0;target.current.y=0}}><boxGeometry args={[size.x*config.scale*1.08,size.y*config.scale*1.08,size.z*config.scale*1.08]}/><meshBasicMaterial transparent opacity={0}/></mesh><group ref={floatRoot}><group ref={driftRoot}><group ref={root} position={[0,0,ground]}><primitive object={gltf.scene} scale={config.scale}/></group></group></group></group>}
function media(q:string){const[v,s]=useState(false);useEffect(()=>{const m=matchMedia(q),u=()=>s(m.matches);u();m.addEventListener("change",u);return()=>m.removeEventListener("change",u)},[q]);return v}export default function DiecastSpike(){const el=useRef<HTMLDivElement>(null),{isActive}=useGpuSceneActivity({id:"lab-diecast",elementRef:el,priority:1}),reduced=media("(prefers-reduced-motion: reduce)"),fine=media("(pointer: fine)");return <div ref={el} style={{height:"min(62svh,44rem)",background:"#080808"}}><Canvas camera={{fov:32,position:config.camera}} frameloop={isActive?"always":"never"} dpr={[1,gpuSceneConfig.desktopMaxDpr]}><color attach="background" args={[0x080808]}/><StudioEnvironment/><ambientLight intensity={.25}/><directionalLight intensity={2.4} position={[5,8,8]}/><directionalLight intensity={.8} position={[-6,3,4]}/><Suspense fallback={null}><Car fine={fine} reduced={reduced}/></Suspense></Canvas></div>}
