"use client";
import { Suspense, useEffect, useRef, useState } from "react";
import { Canvas, useFrame, type ThreeEvent } from "@react-three/fiber";
import { Group, MathUtils } from "three";
import { useGpuSceneActivity } from "@/hooks/useGpuSceneActivity";
import { gpuSceneConfig } from "@/lib/performance/gpu-config";
import StudioEnvironment from "../can/StudioEnvironment";
import TamagotchiModel from "./TamagotchiModel";
import { tamagotchiConfig } from "./tamagotchi-config";
import styles from "./TamagotchiSpike.module.css";
const sceneId = "lab-tamagotchi";
function usePrefersReducedMotion() { const [value, setValue] = useState(false); useEffect(() => { const query = window.matchMedia("(prefers-reduced-motion: reduce)"); const update = () => setValue(query.matches); update(); query.addEventListener("change", update); return () => query.removeEventListener("change", update); }, []); return value; }
function TamagotchiScene({ isHovered, prefersReducedMotion, onHoverChange }: { isHovered: boolean; prefersReducedMotion: boolean; onHoverChange: (value: boolean) => void }) { const motionRootRef = useRef<Group>(null); const floatGroupRef = useRef<Group>(null); const tiltGroupRef = useRef<Group>(null); const velocityRef = useRef(tamagotchiConfig.idleAngularVelocity); useFrame((state, delta) => { const root = motionRootRef.current, floatGroup = floatGroupRef.current, tilt = tiltGroupRef.current; if (!root || !floatGroup || !tilt) return; if (prefersReducedMotion) { velocityRef.current = 0; root.rotation.y = 0; floatGroup.position.y = 0; tilt.rotation.set(tamagotchiConfig.fixedTiltX, 0, tamagotchiConfig.fixedTiltZ); return; } velocityRef.current = MathUtils.damp(velocityRef.current, tamagotchiConfig.idleAngularVelocity * (isHovered ? tamagotchiConfig.hoverRotationMultiplier : 1), 4, delta); root.rotation.y += velocityRef.current * delta; const t = state.clock.elapsedTime; const y = Math.sin(t * tamagotchiConfig.floatAngularVelocity) * tamagotchiConfig.floatAmplitude + Math.sin(t * tamagotchiConfig.floatAngularVelocity * 2 + 0.8) * 0.012; floatGroup.position.y = MathUtils.damp(floatGroup.position.y, y * (isHovered ? 0.55 : 1), 8, delta); tilt.rotation.x = tamagotchiConfig.fixedTiltX + Math.sin(t * 0.7) * tamagotchiConfig.microTiltX; tilt.rotation.z = tamagotchiConfig.fixedTiltZ + Math.sin(t * 0.55 + 0.6) * tamagotchiConfig.microTiltZ; }); const handleOut = (event: ThreeEvent<PointerEvent>) => { if (!event.intersections.some((intersection) => intersection.object.parent)) onHoverChange(false); }; return <group ref={motionRootRef}><group ref={floatGroupRef}><group ref={tiltGroupRef}><Suspense fallback={null}><TamagotchiModel onPointerOut={handleOut} onPointerOver={() => onHoverChange(true)} /></Suspense></group></group></group>; }
export default function TamagotchiSpike() { const elementRef = useRef<HTMLDivElement>(null); const { isActive } = useGpuSceneActivity({ id: sceneId, elementRef, priority: 1 }); const reducedMotion = usePrefersReducedMotion(); const [isHovered, setIsHovered] = useState(false); return <div ref={elementRef} className={styles.spike} data-hovered={isHovered || undefined}><Canvas aria-label="Tamagotchi collectible device" camera={{ fov: 32, position: tamagotchiConfig.cameraPosition }} className={styles.canvas} dpr={[1, gpuSceneConfig.desktopMaxDpr]} frameloop={isActive ? "always" : "never"} gl={{ antialias: true, powerPreference: "high-performance" }} onCreated={({ camera }) => camera.lookAt(0, 0, 0)}><color attach="background" args={[0x080808]} /><StudioEnvironment /><ambientLight intensity={0.18} /><hemisphereLight groundColor={0x11110f} intensity={0.4} /><directionalLight intensity={2} position={[4, 5, 6]} /><directionalLight intensity={0.7} position={[-4, 1.5, 3]} /><directionalLight intensity={0.45} position={[1, -2, 3]} /><TamagotchiScene isHovered={isHovered} onHoverChange={setIsHovered} prefersReducedMotion={reducedMotion} /></Canvas></div>; }
